"""Write a PyInstaller version-info resource so the built EXE carries a real
Windows version (right-click -> Properties -> Details).

Usage:  python tools/gen_version_file.py 1.0.0 build/version_info.txt
"""

import os
import re
import sys

APP_NAME = "MapHarvest"
COMPANY = "MapHarvest"
DESCRIPTION = "MapHarvest - Google Maps business scraper"
COPYRIGHT = "MIT Licensed"

TEMPLATE = """# Auto-generated by tools/gen_version_file.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({maj}, {min}, {patch}, 0),
    prodvers=({maj}, {min}, {patch}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{company}'),
         StringStruct('FileDescription', '{description}'),
         StringStruct('FileVersion', '{version}.0'),
         StringStruct('InternalName', '{app}'),
         StringStruct('LegalCopyright', '{copyright}'),
         StringStruct('OriginalFilename', '{filename}'),
         StringStruct('ProductName', '{app}'),
         StringStruct('ProductVersion', '{version}.0')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def main() -> int:
    if len(sys.argv) < 3:
        print("usage: gen_version_file.py <x.y.z> <output-path>")
        return 2

    version = sys.argv[1].strip().lstrip("vV")
    out_path = sys.argv[2]

    m = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", version)
    if not m:
        print(f"ERROR: version must look like 1.0.0 (got '{version}')")
        return 1

    maj, minor, patch = (int(g) for g in m.groups())
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(TEMPLATE.format(
            maj=maj, min=minor, patch=patch, version=version,
            app=APP_NAME, company=COMPANY, description=DESCRIPTION,
            copyright=COPYRIGHT, filename=f"{APP_NAME}-{version}.exe",
        ))
    print(f"version resource -> {out_path} (v{version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
